exclude: ^.venv/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        exclude: ^src/pipelines/

  - repo: local
    hooks:
      - id: pydoclint
        name: pydoclint
        entry: poetry run pydoclint
        language: system
        types: [python]
        args: ["--style=google", "--check-return-types=True"]
        exclude: ^src/pipelines/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: ^tests/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "--jobs=0",
            "--fail-under=9",
            "--fail-on=F,E",
            "--max-line-length=100",
            "--reports=no",
            # "--good-names=e,f,i,j,k,p,v,x,y,z,x0,x1,z0,z1,tn,fn,tp,fp,auc,fc,bn",
            # "--disable=C0301, C0114, C0115, C0116, E1101, E1121, R0903, R0913, W0511",
            "--disable=C0103,C0114,W0221,W0511,R0913,R0902,R0914,R0917,E1101",
            "--extension-pkg-whitelist=pydantic",
          ]
        exclude: ^tests/


  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry run bandit --skip B614
        language: system
        types: [python]
        exclude: ^tests/|^src/pipelines/

  - repo: local
    hooks:
      - id: export-poetry-requirements
        name: Export Poetry Requirements
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # general file rules
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # file format checks
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      # git related
      - id: check-added-large-files
        args: ["--maxkb=3000"]
      - id: check-merge-conflict
      # python specifics
      - id: name-tests-test
        args: ["--pytest-test-first"]
