name: warprec
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - pip
  - setuptools
  - wheel
  - hyperopt>=0.2.7,<1.0.0
  - mlflow>=2.22.0,<3.0.0
  - numpy>=2.2.2,<3.0.0
  - pandas>=2.2.3,<3.0.0
  - pydantic>=2.10.6,<3.0.0
  - scikit-learn>=1.6.1,<2.0.0
  - scipy>=1.15.1,<2.0.0
  - tabulate>=0.9.0,<1.0.0
  - tensorboard>=2.19.0,<3.0.0
  - torchmetrics>=1.6.2,<2.0.0
  - types-pyyaml>=6.0.12,<7.0.0
  - types-tabulate>=0.9.0,<1.0.0
  - pip:
    - codecarbon>=3.0.0,<4.0.0
    - loguru>=0.7.3,<1.0.0
    - ray[data,serve,train,tune]>=2.42.1,<3.0.0
    - tensorboardx>=2.6.2,<3.0.0
    - torch>=2.6.0,<3.0.0
    - wandb>=0.19.10,<1.0.0
