name: warprec
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12.11
  - pip=25.3
  - setuptools=80.9.0
  - wheel=0.45.1
  - cuda-toolkit=12.6
  - azure-identity>=1.25.1,<2.0.0
  - azure-storage-blob>=12.26.0,<13.0.0
  - hyperopt>=0.2.7,<1.0.0
  - loguru>=0.7.3,<1.0.0
  - matplotlib>=3.10.3,<4.0.0
  - mlflow>=2.22.0,<3.0.0
  - mypy>=1.14.1,<2.0.0
  - narwhals>=2.15.0,<3.0.0
  - numpy>=2.2.2,<3.0.0
  - optuna>=4.5.0,<5.0.0
  - pandas>=2.2.3,<3.0.0
  - polars=1.36.1
  - pre-commit>=4.1.0,<5.0.0
  - pydantic>=2.10.6,<3.0.0
  - pylint>=3.3.3,<4.0.0
  - pytest>=8.3.4,<9.0.0
  - scikit-learn>=1.6.1,<2.0.0
  - scipy>=1.15.1,<2.0.0
  - sphinx>=8.2.3,<9.0.0
  - tabulate>=0.9.0,<1.0.0
  - tensorboard>=2.19.0,<3.0.0
  - tensorboardx>=2.6.2,<3.0.0
  - types-pyyaml>=6.0.12,<7.0.0
  - types-tabulate>=0.9.0,<1.0.0
  - wandb>=0.19.10,<1.0.0
  - pip:
    - bandit>=1.8.2,<2.0.0
    - codecarbon>=3.0.0,<4.0.0
    - furo>=2025.7.19,<2026.0.0
    - nvitop>=1.4.2,<2.0.0
    - pydata-sphinx-theme>=0.16.1,<1.0.0
    - pydoclint>=0.6.0,<1.0.0
    - ray[data,serve,train,tune]==2.50.1
    - ruff>=0.9.3,<1.0.0
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.7.0+cu126
    - --find-links https://data.pyg.org/whl/torch-2.7.0+cu126.html
    - torch-scatter==2.1.2+pt27cu126
    - torch-sparse==0.6.18+pt27cu126
    - torch-cluster==1.6.3+pt27cu126
    - torch-spline-conv==1.2.2+pt27cu126
    - torch-geometric==2.7.0
    - torchmetrics==1.8.2
    - torchdiffeq==0.2.5
    - numba==0.62.1
    - grpcio==1.76.0
