reader:
  loading_strategy: dataset
  data_type: transaction
  reading_method: local
  local_path: tests/test_dataset/movielens.csv
  rating_type: explicit
  sep: ','
splitter:
  test_splitting:
    strategy: temporal_holdout
    ratio: 0.1
models:
  BPR:
    embedding_size: 32
    weight_decay: 0.
    batch_size: 1024
    epochs: 10
    learning_rate: 0.0001
evaluation:
  top_k: [10, 20, 50]
  batch_size: 1024
  metrics: [nDCG, Precision, Recall, HitRate]
